<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();

$product = $_item->getProduct();

$productOptions = $_item->getProductOptions();
if(isset($productOptions["simple_sku"])) {
    $productCollection = \Magento\Framework\App\ObjectManager::getInstance()->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
    $product = $productCollection->addAttributeToSelect('*')->addAttributeToFilter('sku', $productOptions["simple_sku"])->getFirstItem();
}

$_order = $_item->getOrder();
$_store = $_order->getStore();

$_imageHelper = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Catalog\Helper\Image');
$_baseImageUrl = $_store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).'catalog/product';


$product_url= $_item->getProduct()->getProductUrl(); 

?>
<tr>
    <td>
    <a href="<?php echo $product_url ?>"><img style="margin-right:20px;" src="<?= $_imageHelper->init($product, 'small_image', ['type'=>'small_image'])->keepAspectRatio(true)->resize('65','65')->getUrl();?>" alt="<?= __('Product Image');?>"></a>
    </td>
    <td class="item-info<?= ($block->getItemOptions() ? ' has-extra' : '') ?>">
       <a style="text-decoration: none; color: #000; font-weight: bold;" href="<?php echo $product_url ?>"><p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p></a>
        <p class="sku" style="font-size: 12px;"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options" style="font-size: 12px;">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt style="display: inline-block; width: 30%;"><strong><em><?= $block->escapeHtml($option['label']) ?></em></strong></dt>
                <dd style="display: inline-block; width: 50%;">
                    <?= /* @noEscape */  nl2br($block->escapeHtml($option['value'])) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty" style="text-align: center;"><?= (float) $_item->getQtyOrdered() ?></td>
    <td class="item-price">
        <?= /* @noEscape */ $block->getItemPrice($_item) ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId()
    && $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
        ->getGiftMessage($_item->getGiftMessageId())
) : ?>
    <tr>
    <td colspan="4" class="item-extra">
        <table class="message-gift">
            <tr>
                <td>
                    <h3><?= $block->escapeHtml(__('Gift Message')) ?></h3>
                    <strong><?= $block->escapeHtml(__('From:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                    <br /><strong><?= $block->escapeHtml(__('To:')) ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                    <br /><strong><?= $block->escapeHtml(__('Message:')) ?></strong>
                    <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; ?>
